version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_database
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "8080:80"

volumes:
    mysql-data:
